### ISSUE TITLE
"/dev/snd": no such file or directory

### ISSUE THREAD

**Issue by Mino9526** [bestwu/docker-qq#53]
xxx@xxx:~/Applications/QQ$ docker-compose up -d
Starting qq ... error

ERROR: for qq  Cannot start service qq: error gathering device information while adding custom device "/dev/snd": no such file or directory

ERROR: for qq  Cannot start service qq: error gathering device information while adding custom device "/dev/snd": no such file or directory
ERROR: Encountered errors while bringing up the project.

**Comment by Mino9526** [comment]
```
version: '2'
services:
  qq:
    image: bestwu/qq:office
    container_name: qq
    ipc: host
    devices:
      - /dev/snd
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/asroe/Applications/QQ/TencentFiles:/TencentFiles
    environment:
      - DISPLAY=unix$DISPLAY
      - XMODIFIERS=@im=fcitx
      - QT_IM_MODULE=fcitx
      - GTK_IM_MODULE=fcitx
      - AUDIO_GID=29
      - GID=1000
      - UID=1000
 ```
